name: Test schedule3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher le contexte
        run: |
          echo "event_name=${{ github.event_name }}"
          date -u
