name: Test schedule

on:
  push:
    branches:
      - main
  schedule:
    - cron: '21 20,22,0,2,4 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher la date
        run: date
